Squashed 'deps/fmt/' changes from a3370119..64dc8fba
REVERT: a3370119 Update version
REVERT: 1f575fd5 Bump version
REVERT: c7635288 Fix docs, take 2
REVERT: c8ed78e3 Fix docs
REVERT: e07cfb20 Update changelog
REVERT: 1dc7af56 Fix markup
REVERT: f7d21c3a Update changelog
REVERT: a55bcb24 Update changelog
REVERT: 30cb2b31 Remove appveyor config
REVERT: cf8d3c32 Update changelog
REVERT: 3c3cb6f6 Update changelog
REVERT: 91481f25 Detemplatize code_point_length_impl
REVERT: f98048b6 Fix bugs in utf8 decoder (#3056)
REVERT: 4a8e2949 Fix formatting of ranges of code unit types
REVERT: 3a3b0709 Disable bogus -Wstringop-overflow on GCC 11 (#3054)
REVERT: e724bbea Fix wchar_t corner cases
REVERT: 665d9779 Disable non-type template args for nvhpc (#3053)
REVERT: 13d07c6a Apply doc fixes retroactively
REVERT: 391f922a Improve error reporting in format string compilation
REVERT: dc59d3df Fix a warning in gtest
REVERT: 489dabbd Fix decoder on broken utf8 sequences. (#3044)
REVERT: 541cd218 Fix locale name (thanks Mikhail Paulyshka)
REVERT: 1f95c343 Fix sign handling with large code units
REVERT: 779449fd Belarusify test
REVERT: fbb568bc nvhpc/22.3: workaround for c++17 mode. (#3043)
REVERT: 36c23bd5 Prepare for deprecating FindPythonInterp module. (#3040)
REVERT: 9ff0f3a7 Fix docs
REVERT: fd41110d Add MinGW to CI
REVERT: fc23cfbf Fix testsuite on MinGW + MSVCRT
REVERT: fd93b633 Constexpr formatted_size (#3026)
REVERT: 7fb8d33f Fix compile-time width/precision type check
REVERT: 8bd02e93 Reduce conditional compilation
REVERT: d9c1c735 Use is_utf8() in print(std::ostream&, ...)
REVERT: 682e097b Remove -Wl,--as-needed linker option
REVERT: b9087ee5 Suppress unused typedef warning
REVERT: df56fdf8 Clarify docs for compile-time checks
REVERT: 90c48b85 Remove double code execution
REVERT: 5a8b7cd7 Add comment
REVERT: 36a25d75 Reuse detail::string_literal in the chrono formatter
REVERT: 6c9304b2 Replace ParseContext with basic_format_parse_context
REVERT: 24ab9dd1 Remove duplicate method
REVERT: a95dc170 Remove unused condition
REVERT: 5f774c0a I shouldn't be there
REVERT: 6567df7f Update README.rst
REVERT: 6c6b1fbf Workaround a bug in MSVC
REVERT: 9beddd08 Improve CI on Windows
REVERT: 6452e3c9 Fix a typo in example
REVERT: 756822ba Fix Unicode handling for ostream under Windows with libc++. (#3001)
REVERT: 0b2862a1 Range formatter (#2983)
REVERT: 25800006 Add fmt:: namespace to doc (#3009)
REVERT: e9ca7ea4 Suppress a bogus warning
REVERT: 81f1cc74 Improve Unicode handling when writing to an ostream on Windows (#2994)
REVERT: bbcb129e Reduce filesize of the tests on MinGW (#2995)
REVERT: 48e0a592 Implement compile-time checks for dynamic width/precision type
REVERT: bc5c7c50 Fixes IBM XLC behavior with uint128 fallback (#2985)
REVERT: 00adc712 Add a regression test for here be dragons
REVERT: c48be439 Add additional search paths for doxygen on Windows
REVERT: 371f9c71 Fix even in format_dragon
REVERT: 91abfcd6 Suppress an msvc warning
REVERT: deeab54b Remove unused include
REVERT: 688a627d Remove unused constants.
REVERT: 9bb1605f Remove some branches
REVERT: 8061d9af Simplify Dragonbox implementation
REVERT: d82e1a10 Make sure the correct fmod overload is called
REVERT: defa04e7 Fix for EDG frontend (Intel, NVHPC compilers) (#2982)
REVERT: 92d36e82 The n specifier for ranges (#2981)
REVERT: 0db43cf7 Pointless comparison warnings (#2971)
REVERT: 05be7a07 Use FMT_USE_FLOAT128 instead of __SIZEOF_FLOAT128__
REVERT: 2a1b3ac6 Fix large shift in uint128_fallback
REVERT: e1d3d3a3 Exclude recursive ranges from the formatter specialization for ranges (#2974)
REVERT: b761f127 Improve forward using the idea from Jonathan Müller
REVERT: cc192694 Inline std::forward
REVERT: d5e9166f Fixed typo in changelog example.
REVERT: b31d1a75 Add xchar support for fmt::streamed().
REVERT: c4ee7265 Update version
REVERT: fa2eb2d2 Bump version
REVERT: 35f72bf2 Bump version
REVERT: d22f00d7 Update changelog
REVERT: 4e8d2156 Update changelog
REVERT: 84eecb65 Prune CI configs
REVERT: 55727e3b More compile-time checks
REVERT: 1010b7f1 Update docs
REVERT: 2ac51fc4 Update changelog
REVERT: 83113229 Workaround for Microsoft Visual Studio 2022 Internal compiler error.
REVERT: 115e00e0 Replace __cplusplus with FMT_CPLUSPLUS.
REVERT: 94114b05 New CI: Microsoft Visual Studio 2022.
REVERT: d2a23208 Fix partial specialization problem for filesystem for Visual Studio (#2957)
REVERT: 0c06c81d Deprecated implicit conversion of enums to ints for consistency with scoped enums
REVERT: c12b4c0c New CI: GCC-8 C++17, Clang-8 C++17.
REVERT: 99bb5b1d Fix std::variant, std::filesystem::path tests on GCC-8, Clang-7,8.
REVERT: e29c2bc6 Update docs
REVERT: c65e4286 Update changelog
REVERT: 69c24e47 Update changelog
REVERT: 6a775e95 Add support for 'std::variant' in C++17 (#2941)
REVERT: 51535866 Update docs
REVERT: 3ef5caa9 Update docs
REVERT: dccd3e67 Fix docs
REVERT: 9cb02aaa Fix UDLs
REVERT: e6d478f8 Update changelog and docs
REVERT: 2d931b14 Add fmt::streamed
REVERT: 0506a573 Update changelog
REVERT: e8bd2a80 Fix enable_ifs for map formatter (#2944)
REVERT: 7c56e11e Update changelog
REVERT: 69a20db0 Update changelog and fix an apidoc comment
REVERT: 7a2a97c8 Update changelog
REVERT: 56823388 Fix is_formattable for tuple-like types. (#2940)
REVERT: f0de1284 Remove /source-charset:utf-8 compile option.
REVERT: eaa8efb9 Fix ofstream handling in msvc
REVERT: fb991e9d Update changelog
REVERT: 8e47cfd1 fix -Wsign-conversion warning
REVERT: 24718758 Make the tests pass on a CHERI system.
REVERT: b135f1c0 Refactor handling of argument types
REVERT: f61a1e81 Add format_arg_types
REVERT: 48b7e3da Added a FMT_STRING wrapper for system_error() call.
REVERT: 4bb3af7a Improve compile-time checks
REVERT: d02c582b Fix 'duplicate symbol' error.
REVERT: b59d8c3a Make std::filesystem::path formatter utf-8 compatible.
REVERT: 232e21d5 Add utf-8 test for std::filesystem::path formatter.
REVERT: 86446541 Docs: add comment about empty format context range
REVERT: ba50c19e use qualified call to avoid ADL conflict with std::format_to
REVERT: 9d603959 Fix compilation on ppc64
REVERT: a2681aab Debug ppc failure
REVERT: bfc57673 Add support for std.h in Bazel build
REVERT: 798d09bb Debug ppc failure
REVERT: 8c7cf513 Cleanup
REVERT: cdfacb43 Cleanup parse_format_string
REVERT: 926ddd06 Move compile string to detail
REVERT: cb682f36 Move to_string_view to detail
REVERT: 156744ad Simplify fmt::runtime
REVERT: d9c7166c bi_iterator -> base
REVERT: 11316b29 chore: Set permissions for GitHub actions
REVERT: fe6eb792 Cleanup check_format_string
REVERT: 054b1d98 Remove unused include
REVERT: e927149f Cleanup macros
REVERT: 1761e266 Remove FMT_CONSTEXPR_DECL
REVERT: d6b568a6 Cleanup string_view checks
REVERT: c83a5d42 FMT_MSC_VER -> FMT_MSC_VERSION
REVERT: 27cd68c3 Cleanup macros
REVERT: 08be4abb Remove FMT_NVCOMPILER_VERSION
REVERT: 661b1925 Remove FMT_HEADER_ONLY_CONSTEXPR20
REVERT: d1026fa5 Remove extern format_float
REVERT: 7e63b600 Make to_string work with __float128
REVERT: b2ea212c Update README.rst
REVERT: c2fcdc54 Move format_float to format.h for __float128
REVERT: 2b9037a1 Move basic_fp to format.h for compile-time formatting
REVERT: 542785cc Get rid of detail::bits
REVERT: 65dd2ea5 Use write_escaped_string to std::filesystem::path.
REVERT: 9860f67c Improve xchar support for std formatters.
REVERT: 03b1b283 Improve std::filesystem::path formatter.
REVERT: 4f9311e6 Fix definition of error_handler::on_error
REVERT: 652fea45 Visual Studio 2022: fmt/format.h(1526,27): warning C4127: conditional expression is constant #2908
REVERT: 1f9eae7e Add xchar support for write_escaped_string.
REVERT: 90b68783 Skip cmake targets inclusion if fmt::fmt already exists (#2907)
REVERT: ce246aaf Remove deprecated APIs
REVERT: edeb3d80 Remove deprecated APIs
REVERT: 496aff7c Remove deprecated APIs
REVERT: f5cdf7cb Simplify snprintf_float
REVERT: 440512f0 Remove deprecated APIs
REVERT: 621eb80b Remove deprecated APIs
REVERT: 5c7d315d Remove locale.h
REVERT: c6324009 Add initial double-double support
REVERT: 147e8ca5 Fix Windows max mix-up (#2903)
REVERT: 6bf039d7 Add std::thread::id formatter
REVERT: 9730fb01 Fix path formatter
REVERT: f0903ad9 Add a path formatter
REVERT: 8833f386 Merge branch 'master' of github.com:fmtlib/fmt
REVERT: 5ab9d392 Namespace-qualify format_to to avoid conflict with std::format_to
REVERT: af5644c2 Update README.rst
REVERT: 3e28dc02 VS2022 17.2: C4189: 'zero': local variable is initialized but not referenced #2891 (#2892)
REVERT: f6f920a1 Tweak a comment and apply clang-format
REVERT: ae963e44 Implement constexpr isfinite to avoid producing NaN
REVERT: 358f5a7e Make precision computation consistent with width
REVERT: f63afd16 Fixed all clang -Wsigned-enum-bitfield warnings (#2882)
REVERT: 7e4ad401 Add initial support for double-double
REVERT: ffb5e6a7 Suppress a -Wliteral-range warning on Apple M1 (#2861)
REVERT: 5d804ee7 Fix handling of subnormals in exotic FP
REVERT: 86e27ccb Suppress a warning
REVERT: 192f79aa Fix handling of locale separators in FP formatting
REVERT: 395cf0f0 Fix detection of unformattable pointers
REVERT: fc429d18 Avoid overhead on sensible platforms
REVERT: ce7ecdb7 Replace conditional compilation with SFINAE
REVERT: 8751a03a Fix Unicode handling when writing to an ostream
REVERT: c55175a5 Add an issue template
REVERT: a935ac3e MSVC CMake generation optimization (#2852)
REVERT: 22d31b31 Add a __float128 test
REVERT: f607e3e9 Add __float128 support
REVERT: 686de588 Implement 128-bit constant mul in bigint
REVERT: 02eb215f Replace uint128_wrapper with uint128_fallback
REVERT: b4dc7a1d Add 128-bit operations to bigint
REVERT: ef54f9aa Suppress -Wfloat-equal
REVERT: 288c3b92 Remove dead code in ostream.h format_value
REVERT: 96930161 Implement 128-bit operator+= for uint128_fallback
REVERT: b41890c1 Make arg_mapper SFINAE-friendly again
REVERT: e2408f37 Check if formatter is not defined if there is format_as
REVERT: db5b8993 Fix formatting of std::byte via format_as
REVERT: 1c83eaf7 Fix incompatible between Jinja2 >= 3.1 and sphinx 3.3.0
REVERT: 5379063b Fixed clang -Wreserved-identifier warings
REVERT: b591fc87 Fixed all clang -Wreserved-id-macro warnings (on macOS at least)
REVERT: 17dda583 constexpr -> const for portability
REVERT: 7ffe87c0 Fix docs
REVERT: 3c4273dd Simplify UDL
REVERT: 36d95c9f Fix docs
REVERT: 44abd1f4 Update signatures in docs and ostream.h
REVERT: db745986 Workaround broken std::numeric_limits
REVERT: 8271e43e Improve __float128 support and use constexpr
REVERT: 3f9b7433 Improve __float128 support
REVERT: 71778e8b Specialize float_info for __float128
REVERT: f024565c Improve exponent handling in Dragon
REVERT: e7f31f5c Cleanup format_dragon
REVERT: 3c61799f Cleanup fuzzing mode
REVERT: 4e39e130 Remove xchar.h include from ostream.h
REVERT: ac0d9d5f Issue #2816: also strip named-arg for the fallback formatter
REVERT: 4ad90578 Fix #2818: diagnose unformattable arguments in unpacked case
REVERT: 17ba99c1 Fix #2817: add compile-time checking to ostream overloads of fmt::print
REVERT: 3d19be28 Fix #2816: strip named argument wrappers for compile-time checking
REVERT: c076a54a Move snprintf_float to format.h
REVERT: 0419d238 Add FMT_USE_FLOAT128
REVERT: 69396347 Update color.h (#2815)
REVERT: c51604a0 Reduce the number of configs
REVERT: 587dc994 Remove windows-2016 env no longer suppported by GA
REVERT: 1f3d44b8 Update std::tm/chrono docs
REVERT: bc654faf Add is_floating_point that works with __float128
REVERT: 26bffce6 Simplify basic_memory_buffer
REVERT: ed18ca3e Implement isnan
REVERT: a204b8dd Add initial __float128 support
REVERT: b6b003b0 Cleanup test
REVERT: f2543b0a Add initial support for 128-bit floats
REVERT: 72f48756 Simplify float_info
REVERT: f91f61cd Reuse num_significand_bits
REVERT: 9a1beab5 Workaround Windows API garbage
REVERT: a8fe8bec Fix compilation error for ranges with ADL `begin`/`end` (#2807)
REVERT: f6bcb25e Remove extra dot
REVERT: b4a4189d Fix handling of implicit bit
REVERT: 32d477e5 Add `styled` in documentation (#2805)
REVERT: 0b7c045a Simplify _cf
REVERT: c10fffec Make _cf visible in the doc build
REVERT: dcfbe4a7 Document output_file default behavior correctly (#2803)
REVERT: 8c9bc070 Implement styled arguments (#2793)
REVERT: 5bc39d36 Eliminate intel compiler warnings (#2802)
REVERT: e3d688e7 Fix warning C4251: class fmt::v8::file needs to have dll-interface (#2797)
REVERT: 8d4f3e91 Update docs
REVERT: 0cef1f81 Fixing formatting of certain kinds of ranges of ranges. (#2787)
REVERT: 5c0d6564 Fix apt install
REVERT: d416a995 Update README.rst
REVERT: 3f67a124 Update README.rst
REVERT: cc57e359 Update godbolt link in the readme (#2789)
REVERT: 86477f7e Fix size computation
REVERT: 0742606f Fix Conversion Warning (#2782)
REVERT: 1ba69fb5 Remove snprintf FP fallback
REVERT: ea6f0bf0 Minor cleanup
REVERT: 1a18a2f3 Fixing "C4127: conditional expression is constant" Visual Studio 2022 warning in pedantic mode (#2783)
REVERT: 4fcacea3 Parameterized fp on significand type
REVERT: cf940ae8 Simplify to_decimal
REVERT: 70dc3de0 Update format.h
REVERT: cbc59ca8 Clear moved from memory buffer
REVERT: ea3d326c Fix clang -Wliteral-range warning (#2779)
REVERT: aad44f28 Add fmt::enums::format_as
REVERT: 1319719a Add underlying_t
REVERT: af5d8004 Limit Dragonbox to supported FP formats
REVERT: 7b964209 Remove unused include
REVERT: a0b43bfa Add support for 96-bit long double
REVERT: 2c8cd2db Fix handling of zero precision
REVERT: b6d56170 Remove unnecessary inline
REVERT: 05432e57 Use consistent indentation
REVERT: 47da218c Remove uintptr_fallback
REVERT: 4ddab890 Merge accumulator into int128_fallback
REVERT: d38f72af Refactor fallback ints
REVERT: 15c2a3ba int128_t -> int128_opt
REVERT: 532a69a6 Fix handling of 96-bit long double with -m32
REVERT: d8e1dd4a improve installing headers
REVERT: ae25f796 add ability to build Apple framework using CMAKE_FRAMEWORK
REVERT: ce93a66d Implement a fallback uint128_t
REVERT: 6a134640 Include 128-bit with other signed integers in specifier check
REVERT: 70de324a Apply 2746 fix for NVidia compiler also (#2770)
REVERT: a1ea3e01 Move built-in formatter specialization to core
REVERT: 161059dd Add support for extended precision FP
REVERT: c4c6b42d Bump version
REVERT: 21785040 Fix markup
REVERT: 2b6f7fc7 Add partial support for extended precision FP
REVERT: 0a24a071 Clz builtin may be not constexpr (Issue #2761) (#2762)
REVERT: ba6f89c7 Update .bazelversion (#2766)
REVERT: 5594edaf Address https://github.com/fmtlib/fmt/issues/2763 (#2765)
REVERT: 10e3b83a Replace ``make_args_checked`` with ``make_format_args`` (#2760)
REVERT: c48353cb Update docs
REVERT: 083510f0 Add FMT_CONSTEXPR to rotr instead
REVERT: dba99bc8 Revert adding constexpr to rotr to satisfy C++11 compilers
REVERT: c04af4bf Simplify remove_trailing_zeros
REVERT: b348caa9 Remove some C-style casts for consistency
REVERT: c8bd1e64 Simplify remove_trailing_zeros
REVERT: 9b23e9dc Fix wrong comment/refer to a correct reference
REVERT: 69f2c550 Remove std:: infront of uint32_t/64_t & add constexpr to rotr
REVERT: 9b62310f Fix some conversion issues
REVERT: 08d12f31 Fix typo
REVERT: dbddb1d0 Remove literal separator to satisfy some compilers
REVERT: 7dbe3dcd Recover log10_2_significand
REVERT: 10642e60 Optimize remove_trailing_zeros
REVERT: 7b4323e1 Add rotr
REVERT: f1bd6f77 Check r < deltai first, because that is the major branch chosen for short inputs
REVERT: 5d8eb6a1 Reflect the new paper   - Change constants appearing in log & division computations   - Rename beta_minus_1 to beta
REVERT: 8e2e4d40 Suppress a gcc warning
REVERT: a44716f5 Workaround to Intel compiler (#2758)
REVERT: c71b0701 Add missing const qualifier (#2755)
REVERT: ecd6022c Update docs
REVERT: afbcf1e8 Remove legacy C locale wrapper
REVERT: 90325d09 Fix stored type detection
REVERT: e2ba01fc Fix overload ambiguity in print
REVERT: 17b362f7 Simplify ostream opt-in API
REVERT: a5a7e3a2 Update docs
REVERT: f055ebbd Make ostream operators opt in to reduce the risk of ODR violations
REVERT: 8a21e328 Remove problematic constructibility check
REVERT: 31e743d0 Don't use ostream for types convertible to string_view
REVERT: 35c0286c Simplify byte handling
REVERT: c7173a36 Drop :: and fix formatting
REVERT: 3e8372b9 qualify unqualified calls to format in compile.h (#2742)
REVERT: a34a97cc Supporting ? as a string presentation type (#2674)
REVERT: ae1aaaee Fix access mode of files created (#2530) (#2733)
REVERT: 1557ab76 Add format_as for enums
REVERT: b00a1eac Fixes NVIDIA HPC compiler and Intel ICC compatibility (#2732)
REVERT: a7aecbfc Remove an old mingw workaround
REVERT: dfcc730c Making target_compile_options PRIVATE, fix #2726, fix #2507
REVERT: f7a809be Clarify the choice of magic numbers and compute the most magic one
REVERT: 09fde7f4 Add fmt::underlying for enum classes
REVERT: 0014024a Don't rely on transitive includes
REVERT: c2850055 FMT_NOEXCEPT -> noexcept
REVERT: 6240d020 Improve comments
REVERT: 925b744a Improve comments
REVERT: 22b14ff2 Simplify cache recovery
REVERT: 3dc26b44 Make a fallback path more compiler-friendly
REVERT: 2e4038bf Simplify lines with __builtin_addcll and friends
REVERT: 76336b4f Replace noexcept with FMT_NOEXCEPT
REVERT: 91819834 Fix syntax errors
REVERT: 74097a14 Remove now-unused stuffs
REVERT: 21a1c533 Fix typo
REVERT: 04eea0f0 Remove now-unused stuffs
REVERT: 35a468ed Simplify integer checks
REVERT: 1882a7a2 Replace Dragonbox cache which allows simpler cache recovery & integer checks
REVERT: f4dd1b1b Simplify Dragonbox Step 3.
REVERT: 70561ed1 Minimize the usage of built-in 128-bit ints It usually generates slower code than manual handling.
REVERT: cdf1a3b5 Fix codecvt warning (#2408) (#2725)
REVERT: b8b037e9 Fix -Wconversion warning  (#2724)
REVERT: 5985f0a7 Fix overflow for chrono durations (#2722)
REVERT: 8f8a1a02 Fix handling of formattable types implicitly convertible to pointers
REVERT: b02e5af5 fmt::join support FMT_COMPILE (#2720)
REVERT: 58fb7823 Improve docs
REVERT: 4fe6129d Fix FMT_NOEXCEPT definition
REVERT: c056a009 Docs: Fix link to "Compile-time Format String Checks" section (#2712)
REVERT: 7c12118c Deprecate buffered_file::fileno
REVERT: 2a09d468 Use noexcept unconditionally
REVERT: a126b4d8 Check if right shift is arithmetic
REVERT: 9ff91b18 Simplify write_fractional_seconds
REVERT: d9f045fb Fix a UB in chrono
REVERT: c06bef72 Adding comments for range formatting. (#2706)
REVERT: 3c98f1a4 Comment style
REVERT: 6e0f1399 Supporting nested format specs for ranges. (#2673)
REVERT: 0102101a Make colored print handle UTF-8 (#2701)
REVERT: 4ac5269b Update ChangeLog.rst
REVERT: b6f4ceae Update version
REVERT: 15f812da Update changelog
REVERT: 6884aab4 Update changelog
REVERT: 88ec4e70 Bump version
REVERT: dd3d2490 Update changelog
REVERT: 739055ae Fix apidocs
REVERT: dbbd711f Suppress a warning
REVERT: 98cbb6a4 Fix ABI compatiblity issue
REVERT: 214cf13f Fix endianness bug in write_digit2_separated (#2699)
REVERT: 17a5c808 Restore FMT_API on error_handler::on_error() (#2696)
REVERT: fc1783fc Avoid undefined symbols with mingw-w64 (#2692)
REVERT: 1b193e7b Deprecate more
REVERT: 8e59744b Switch to new github auth mechanism
REVERT: 7081a6aa Update version

git-subtree-dir: deps/fmt
git-subtree-split: 64dc8fbada9898fccddce0dda3cb0c9695712a3d